export enum ResourceMSG {
    CREATE = 'CREATE_RESOURCE',
    FIND_ALL = 'FIND_RESOURCES',
    FIND_ONE = 'FIND_RESOURCE',
    UPDATE = 'UPDATE_RESOURCE',
    DELETE = 'DELETE_RESOURCE',
}

export enum ParticipantMSG {
    CREATE = 'CREATE_PARTICIPANT',
    FIND_ALL = 'FIND_PARTICIPANTS',
    FIND_ONE = 'FIND_PARTICIPANT',
    UPDATE = 'UPDATE_PARTICIPANT',
    DELETE = 'DELETE_PARTICIPANT',
}